library/books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', views.book_list, name='book_list'), #homepage
    path('<int:book_id>', views.book_view, name='book_view'), #read book details
    path('new', views.book_create, name='book_new'), #create new book object
    path('edit/<int:book_id>', views.book_update, name='book_edit'), #update book
    path('delete/<int:book_id>', views.book_delete, name='book_delete'), #delete book
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
]

library/books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return f"ID: {self.id} Title {self.title}"

library/books/views.py
from django.shortcuts import render, redirect
from django.forms import ModelForm
from books.models import Book

# Create your views here.
class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'pages']

def get_book(book_id):
    return Book.objects.get(id=book_id) 

def book_list(request):
    books = Book.objects.all()
    data = {'all_books': books}
    return render(request, 'books/book_list.html', data)

def book_view(request, book_id):
    book = get_book(book_id)
    data = {'book': book}
    return render(request, 'books/book_detail.html', data)

def book_create(request):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books:book_list')
    return render(request, 'books/book_form.html', {'form': form, 'new_or_edit': 'New'})

def book_update(request, book_id):
    book = get_book(book_id)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books:book_list')
    return render(request, 'books/book_form.html', {'form' :form, 'new_or_edit': 'Edit'})

def book_delete(request, book_id):
    book = get_book(book_id)
    if request.method=='POST':
        book.delete()
        return redirect('books:book_list')
    return render(request, 'books/book_confirm_delete.html', {'object':book})

library/books/templates/books/book_confirm_delete.html
<h1>Book Delete</h1>
<form method="post">{% csrf_token %}
  Are you sure you want to delete "{{ object.title }}" ?
  <input type="submit" value="Submit" />
</form>

library/books/templates/books/book_detail.html
<h1>Book Details</h1>
<h2>Title: {{ book.title }}</h2>
Pages: {{ book.pages }}
<hr/>
<a href="{% url 'books:book_list' %}">Back</a>

library/books/templates/books/book_form.html
<h1>Book Form: {{ new_or_edit }}</h1>
<form method="post">{% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Submit" />
</form>

library/books/templates/books/book_list.html
<h1>Books</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Pages</th>
      <th>View</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    {% for book in all_books %}
      <tr>
        <td>{{ book.title }}</td>
        <td>{{ book.pages }}</td>
        <td><a href="{% url 'books:book_view' book.id %}">view</a></td>
        <td><a href="{% url 'books:book_edit' book.id %}">edit</a></td>
        <td><a href="{% url 'books:book_delete' book.id %}">delete</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'books:book_new' %}">New</a>